### PR TITLE
fix: convert references to absolute paths for proper parent directory handling and deduplication

### LINKED ISSUE #50: bundle path issues
I have some $ref like `../xxx.yaml#/components/schemas/Xxx` in my main openapi yaml file, refering to a parent folder yaml.
It seems it's not bundled properly and stays as ../.

The bundle feature works as expected with redocly cli, so i know it's not an issue with my spec.

If needed i can create a reproducible sample.

### PR DESCRIPTION
**Pull request by TristanSpeakEasy**
## Description

Fixes #50 - Parent directory references (`../`) were not being bundled correctly during the bundling process.

## Problem

When bundling OpenAPI documents with references using parent directory notation (e.g., `../common.yaml#/components/schemas/Schema`), these references were not being properly resolved and bundled. Instead, they remained as `../` references in the output, which breaks the bundled document.

This was reported by @vincentserpoul with a [reproducible example](https://github.com/vincentserpoul/openapi-speakeasy-issues).

## Solution

Modified `handleReference()` to convert ALL references (internal, external, and parent directory) to absolute paths before tracking them. This ensures:

- **Consistent deduplication**: References from different files pointing to the same schema are correctly identified as duplicates
- **Parent directory resolution**: `../` references are properly resolved to their absolute paths
- **Proper bundling**: All external references are correctly bundled into the components section

### Core Fix
- `handleReference()` now converts all references to absolute paths using filepath operations
- References are tracked consistently regardless of their original notation (relative, absolute, or parent directory)

### Code Quality Improvements (DRY/YAGNI)
- Added `isInternalReference()` helper - eliminates ~22 lines of duplication
- Added `extractSimpleNameFromReference()` helper - eliminates ~60 lines of duplication
- Added `findCircularReferenceMatch()` helper - eliminates ~26 lines of duplication  
- Removed unused `parentLocation` parameter (~110 lines total reduction)

## Test Results

✅ All bundle and inline tests passing (8/8)
✅ New comprehensive test case for issue #50 passing  

## Test Case

Added `TestBundle_Issue50_Success` with test data from the issue reproducer, covering:
- Parent directory references (`../common.yaml`, `../country.yaml`)
- Nested schemas with external references
- Proper component name generation for bundled schemas

### CODE REVIEW

File: openapi/localize.go [hunk 1]
```diff
@@ -833,3 +833,50 @@ func normalizeFilePath(filePath string) string {
...
+			if classification.IsFragment {
+				r = relPath + r
+			} else {
+				if ref.GetURI() != "" {
+					r = filepath.Join(filepath.Dir(relPath), r)
+				} else {
+					r = filepath.Join(relPath, r)
+				}
+			}
+		}
```
Comment (BlakeTheAwesome) [inline openapi/localize.go:897]: We're not handling the errors here (or below from `ClassifyReference`).
If that's intentional because there are expected errors of some kind, we should comment that, otherwise we should propagate the error somehow.

File: openapi/localize.go [hunk 2]
```diff
@@ -833,3 +833,50 @@ func normalizeFilePath(filePath string) string {
 
 	return cleanPath
 }
+
+func handleLocalizeReference(ref references.Reference, parentLocation, targetLocation string) (string, *utils.ReferenceClassification) {
+	r := ref.String()
+
```
Comment (BlakeTheAwesome) [inline openapi/localize.go:873]: Is the purpose of this function to resolve references, except keep them relative to the parentLocation?
I couldn't deduce that from the function name, or why that might be desired over the full resolution in `handleReference`.
Maybe a comment stating when this is suitable might be good.
